// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABoql3vba9pZtIJShm-DyuWne4FYcmarg',
    appId: '1:437953463717:android:7e045c68e2d00180c1144c',
    messagingSenderId: '437953463717',
    projectId: 'sattagames-games-8a533',
    storageBucket: 'sattagames-games-8a533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADB0LoCTIcZCsBVV2io2w5h8xPrceKIt0',
    appId: '1:437953463717:ios:fa5c3e39a0de09e1c1144c',
    messagingSenderId: '437953463717',
    projectId: 'sattagames-games-8a533',
    storageBucket: 'sattagames-games-8a533.firebasestorage.app',
    androidClientId: '437953463717-g7djnrtjb0bjinlhlj7k98si15q8o4h0.apps.googleusercontent.com',
    iosClientId: '437953463717-r4ejilqgb7oiv2m8b8ok1m31nnam76pi.apps.googleusercontent.com',
    iosBundleId: 'com.sattagames.sattagames',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAmnbL3kryTEWdSzYt-jOs1PbWnl6HLl0',
    appId: '1:437953463717:web:7857cdeffad072b5c1144c',
    messagingSenderId: '437953463717',
    projectId: 'sattagames-games-8a533',
    authDomain: 'sattagames-games-8a533.firebaseapp.com',
    storageBucket: 'sattagames-games-8a533.firebasestorage.app',
  );

}